version: '2.4'
services:
  hasteserver:
    container_name: hasteserver
    depends_on:
      - redis
    environment:
      PORT: 8290
      STORAGE_DB: 2
      STORAGE_EXPIRE_SECONDS: 21600
      STORAGE_HOST: redis
      STORAGE_PASSWORD: redis
      STORAGE_PORT: 8287
      STORAGE_TYPE: redis
    image: 'skyrabot/haste-server:latest'
    networks:
      - skyra
    ports:
      - '8290:8290'
    restart: always

  influx:
    command: 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt'
    container_name: influxdb
    image: 'influxdb:2.7-alpine'
    networks:
      - skyra
    ports:
      - '8285:8086'
    restart: always
    volumes:
      - 'influx-data:/var/lib/influxdb2'

  postgres:
    container_name: postgres
    image: 'postgres:16-alpine'
    networks:
      - skyra
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skyra

  redis:
    command: 'redis-server --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - skyra
    ports:
      - '8287:8287'
    restart: always

  skyra:
    build:
      context: ../
    container_name: skyra
    depends_on:
      - hasteserver
      - influx
      - postgres
    env_file:
      - ../src/.env.development
      - ../src/.env.development.local
    image: 'skyrabot/skyra:latest'
    networks:
      - skyra
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

volumes:
  postgres-data:
    external: true
  influx-data:
    external: true

networks:
  skyra:
